/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CatastramiteTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CatastramiteWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}